### ISSUE TITLE
Next Sentence Prediction using Phi-2

### ISSUE THREAD

**Issue by cderinbogaz** [textcortex/desktop-app#3]
Hey @yaredtsy 

I have seen your tests and tried out Phi-2 model. It runs extremely fast and it seems that we can do the next sentence prediction using this model locally.

Next sentence prediction is simple, just like copilot predicting and autocompleting the next code block, we will do the same thing using phi-2 model.

This is a feature that we have implemented in the past using chrome extension but in the end the lag was too much that we decided to disable it.

The value this might create for our users is immense! Think about having the github copilot like interaction while writing emails and discord messages, it would be a crazy productivity boost!

- [ ] Implement autocomplete using phi-2
- [ ] Here is an example request for you to use for this purpose:
```bash
curl http://localhost:11434/api/generate -d '{
  "model": "phi",
  "prompt": "Hello Ceyhun,\nI noticed that you had been using TextCortex for a while, but then stopped suddenly.",
  "options": {
    "stop": ["\n"]
  },
  "raw": true,
  "stream": false
}'
```
The stop parameter makes it sure that it stops at the end of a sentence.

- [ ] Implement the interface like github copilot, show the autocomplete a bit lighter then the current text. UX will be the same.
- [ ] BONUS: When pressed the up/down arrow, it shows the other text generation options. Normally opeanai has 'n' parameter that produces multiple options from same prompt. This would be effective for generating multiple options for the users.
- [ ] BONUS2: How would text streaming would look with the autocomplete? Can we reduce the latency to make the UX more addictive? Let's give it a try.

**Comment by cderinbogaz** [comment]
https://twitter.com/vietdle/status/1748284264238490038?s=20

**Comment by abrehamgezahegn** [comment]
Quick comment on UI.  This kind of seamless autocomplete UI might be possible to do in our own editor .  But it's going to be complex or even impossible to implement it for third party editors like gmail. 
 
![Image](https://github.com/textcortex/desktop-app/assets/41052674/93d86904-54fc-43e2-a32b-ad9ee76cbf3f)

So just a heads up about the complexity.
